[gspread]
type = "service_account"
project_id = "future-dynamics-423418-u6"
private_key_id = "c7fba536c69f09cfd1fa1b5b2149f29c08763a0b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCnzWjpTbql6qt+
tnnS8MGZe4joGmofwRwPwPk7BEtHekSjsH8wOZjpRfkxLU1ptA4aPdwbOfo4euYm
U91JjgIdvXqGb5SVtZaUza95fIhSlpP3KfPjPETgs3Dob1RZWvpSyD//lpKqQOGL
8TpgeY5R10qVmb+3H9UdiK68HUsOiNzqjRoWILoUCRg84zTD2aBhJ+5pkiWrKupC
y6r4OlGoHsfKvkCnTDm7US7V/GAAvicryD3Fm8Xd7EZntGm1dLT3tWRAfDgyGeam
p1KW+Rf2C7vN5ePDECUZn8z1BlLg11TO5cgEFyXvBHxtbxnYZ3Et409nyoYLMKu3
XmYJPz1RAgMBAAECggEAAtpo70FFbC7KTbRClrCbShsh9SMF15ZhU28/jZ5WvVdk
irf54aheY5EEr1kK2Ozufx8QJV0Iq88t0fcDwI1r7HTdUXiHjpLGMFoy9/ODHzcK
Owij6fg2CkViz8DyLowad4U0zrQRDa4JZ7y+oQdQFoTSSCrov0SzoKCYqqrWLOAQ
epYe9eYDrKLM7Drsj3oOopmHf/zh8NPYKheNRnGBPqPdaAOwuQUMGJm7xfMCBfCj
UR4G4QXZPwSS0zhDa5EEwmBH1FO/IXmb0Ekjf28SWTOOxvyWkZV554xqqv2scMLw
Nng8+ySk89abrGTKVyT3FXbp02ETAbHbPDPPnO1jNQKBgQDastT2yva4NobiMkVL
CaYJnnY5F+HWVMLt6pVjiqWFgzw81jYzV/dEszl+IyEKdHXu68EhJhAJ7U6G6O64
JYa2ll8RD8FxIamjJfnJOWi83Dp71Tdt5es+638Y2S5kAC11bfjNfU1fOh+P+xqN
2HIRRO9M73+qv9KuEQqS7fDt3wKBgQDEbERhKgL5Xm7wMgNZqzQZZ5rxFZBRFr4j
QsJBdMDmwoihMMatMdNcVu4s+x66pI7+y9tPYgot14pBuaPtyqQFaUrKgyX1RDBB
OsXwJ5lJ9hO5c7wd6bFOtBC5wis6NPclRvBSMnxB4t2H+dfczfWg5woS8YnKp0rJ
LiqD1QHazwKBgG2gv4iG7W4iRzMUKBAZYhXoTTMJebfK/Xvt37zqP1bSFlwYtUq/
ib/yZ5uHWIS5JHUD0OghAGE5h+ew1BmTFhhpAHa5AysGyNZzrubj1FD3xIlWtFZu
rqH3wtpd5BdUz3TSD6pSaXqW1EOEiCcanPNzLtHOLJ0XUzDWcgp9JAzZAoGAXUVL
8xeP8fn1k/krvhid1LJt0Kz8qoSyJOw+cfaO4wTc/C29KeDPDLn6v0E/hkE95Z/H
tBpJ2xrOfAc64F+pIyisax17mMuYXmEaPL+Q+p3vH9DlMw8VMtouVwbsn+cmtHzL
AT0X4/FmYHszFZZ3XMBY+EXZuHFYAc/6QD+VceECgYEAvDzDFZ+ETgNx3HT+phOQ
GKxZa0n8yJiRLEZ9a/8qaOMycnIh8xrlV5+DHFoOuTbCf6E5b0kLBNW5y3UKJEjE
tqNJsk7eaADd4zYreObeiUWvQgI0tYg3BLHOS0gxCbjTBaA1YRHag4WpHLQE9BmF
F9Dx8DtriIVlVPU0AtRRZck=
-----END PRIVATE KEY-----
"""
client_email = "weather-station@future-dynamics-423418-u6.iam.gserviceaccount.com"
client_id = "117660190919284818065"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/weather-station%40future-dynamics-423418-u6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
