[gspread]
type = "service_account"
project_id = "future-dynamics-423418-u6"
private_key_id = "c7fba536c69f09cfd1fa1b5b2149f29c08763a0b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCnzWjpTbql6qt+
...
F9Dx8DtriIVlVPU0AtRRZck=
-----END PRIVATE KEY-----
"""
client_email = "weather-station@future-dynamics-423418-u6.iam.gserviceaccount.com"
client_id = "117660190919284818065"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/weather-station%40future-dynamics-423418-u6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
